# ### create DB
# POST http://127.0.0.1:4000/api/v0/db/books
# Content-Type: application/json

# ### Delete DB
# DELETE http://127.0.0.1:4000/api/v0/db/books
# Content-Type: application/json

# ### Update DB
# PUT http://127.0.0.1:4000/api/v0/db/books
# Content-Type: application/json

# {
#     "name":"name"
# }

### createTable
POST http://127.0.0.1:4000/api/v0/db/books/table/people
Content-Type: application/json

{
    "name": "text",
    "age": "number"
}

### deleteTable
DELETE http://127.0.0.1:4000/api/v0/db/books/table/people
Content-Type: application/json

### addRow
PUT http://127.0.0.1:4000/api/v0/db/books/table/people
Content-Type: application/json

{
    "name": "Jaime",
    "age": 25
}

# ### addRow
# DELETE http://127.0.0.1:4000/api/v0/db/books/table/people/0
# Content-Type: application/json

# ### addRow
# PUT http://127.0.0.1:4000/api/v0/db/books/table/people/0
# Content-Type: application/json

# {
#     "name": "Jaime",
#     "age": 25
# }

### getAll
GET http://127.0.0.1:4000/api/v0/db/books/table/people
Content-Type: application/json

### getOne
GET http://127.0.0.1:4000/api/v0/db/books/table/people/2
Content-Type: application/json

### getOneTest
GET http://127.0.0.1:4000/api/v0/db/test
Content-Type: application/json