### Backend
GET http://127.0.0.1:3000/api/v0
Content-Type: application/json

### DB
GET http://127.0.0.1:3000/DBcreateTable
Content-Type: application/json

### DB
GET http://127.0.0.1:3000/DBaddRow
Content-Type: application/json

### DB
GET http://127.0.0.1:3000/DBgetAll
Content-Type: application/json